/*
 * generated by Xtext
 */
package felix;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FelixRuntimeModule extends felix.AbstractFelixRuntimeModule {

}
