/*
* generated by Xtext
*/
package felix.ui.contentassist;

import felix.ui.contentassist.AbstractFelixProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FelixProposalProvider extends AbstractFelixProposalProvider {

}
