/*
 * generated by Xtext
 */
package felix.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import felix.ui.highlighting.FelixHighlightingConfiguration;
import felix.ui.highlighting.FelixSemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FelixUiModule extends felix.ui.AbstractFelixUiModule {
	public FelixUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return FelixSemanticHighlightingCalculator.class;
	}
	
	public Class<? extends org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return FelixHighlightingConfiguration.class;
	}
	
}
